project:
  type: website

website:
  title: "<%= title %>"
  navbar:
    left:
      - href: index<%= ext %>
        text: Home
      - about<%= ext %>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

<% if(editor){ %>editor: <%= editor %><% } %>
