project:
  type: website

website:
  title: "<%= title %>"
  navbar:
    right:
      - about<%= ext %>
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

<% if(editor){ %>editor: <%= editor %><% } %>
